#!/usr/bin/env python3
"""
push_pins_to_sheets.py
Reads staged _pin_queue/*.json files, appends rows to the correct Google Sheets,
then moves processed files to _pin_queue/sent/.
Run ONLY after GitHub Pages build is confirmed live (called by autopublish.sh).
"""

import argparse
import json
import os
import sys
import shutil
from datetime import datetime
from pathlib import Path

REPO_DIR = Path(__file__).parent


def log(msg):
    print(f'[{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}] {msg}', flush=True)


def load_env():
    env_path = Path.home() / '.env'
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                k, _, v = line.partition('=')
                os.environ.setdefault(k.strip(), v.strip())


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--slugs', default='', help='Comma-separated slugs to process (empty = all queued)')
    args = parser.parse_args()
    slug_filter = set(s.strip() for s in args.slugs.split(',') if s.strip())

    load_env()

    try:
        import gspread
        from google.oauth2.service_account import Credentials
    except ImportError:
        log('ERROR: gspread not installed. Run: pip install gspread google-auth --break-system-packages')
        sys.exit(1)

    key_file = REPO_DIR / 'happypet-sheets-key.json'
    if not key_file.exists():
        log('ERROR: happypet-sheets-key.json not found')
        sys.exit(1)

    queue_dir = REPO_DIR / '_pin_queue'
    sent_dir  = queue_dir / 'sent'
    queue_dir.mkdir(exist_ok=True)
    sent_dir.mkdir(exist_ok=True)

    queue_files = sorted(queue_dir.glob('*.json'))
    if slug_filter:
        queue_files = [f for f in queue_files if f.stem in slug_filter]
        log(f'Slug filter active — processing {len(queue_files)} file(s): {slug_filter}')
    if not queue_files:
        log('No queued pins found — nothing to do')
        return

    # Auth
    scopes = ['https://www.googleapis.com/auth/spreadsheets']
    creds  = Credentials.from_service_account_file(str(key_file), scopes=scopes)
    gc     = gspread.authorize(creds)

    dog_id = os.environ.get('HAPPYPET_SHEET_ID_DOGS', '')
    cat_id = os.environ.get('HAPPYPET_SHEET_ID_CATS', '')

    # Topical sheet IDs — all HAPPYPET_SHEET_ID_* except Dogs/Cats
    topical_ids = {
        k: v for k, v in os.environ.items()
        if k.startswith('HAPPYPET_SHEET_ID_')
        and k not in ('HAPPYPET_SHEET_ID_DOGS', 'HAPPYPET_SHEET_ID_CATS')
    }

    # Slug → topical sheet env key (generated by generate_posts.py, stored in slug_topical_map.json)
    slug_topical_map = {}
    map_path = REPO_DIR / 'slug_topical_map.json'
    if map_path.exists():
        slug_topical_map = json.loads(map_path.read_text())

    today     = datetime.now().strftime('%Y-%m-%d')
    processed = 0
    failed    = 0

    for qf in queue_files:
        try:
            # Dedup guard — skip if already sent in a previous run
            if (sent_dir / qf.name).exists():
                log(f'  SKIP (already sent): {qf.name}')
                continue

            data        = json.loads(qf.read_text())
            title       = data['title']
            article_url = data['article_url']
            description = data.get('description', '')
            image_url   = data['image_url']
            species     = data.get('species', 'both')
            slug        = data.get('slug', '')

            row = [title, article_url, description, image_url, today, 'NO']

            targets = []
            if species in ('dog', 'both') and dog_id:
                targets.append(('Dogs', dog_id))
            if species in ('cat', 'both') and cat_id:
                targets.append(('Cats', cat_id))

            topical_key = slug_topical_map.get(slug)
            if topical_key:
                topical_id = topical_ids.get(topical_key)
                if topical_id:
                    targets.append((topical_key, topical_id))

            for label, sheet_id in targets:
                sh = gc.open_by_key(sheet_id)
                sh.get_worksheet(0).append_row(row)
                log(f'  SHEET: appended to {label} — {title}')

            shutil.move(str(qf), str(sent_dir / qf.name))
            log(f'  SENT: {qf.name} → _pin_queue/sent/')
            processed += 1

        except Exception as e:
            log(f'  FAIL: {qf.name} — {e}')
            failed += 1

    log(f'DONE — {processed} pinned, {failed} failed')


if __name__ == '__main__':
    main()
